#! /usr/bin/python

import os, re

##### 0. download monthly .pnt files to /mnt/scratch/... on cloud0-a, and run script in that
#####    dir to convert to yearly average pnt files, then transfer results to
#####    data/yearly-avg-pnt-files in this dir.


#####
##### 1. Convert yearly avg files from pnt to pkz format in dir _data/yearly-avg-pkz-files_:
#####
#---| os.system("mkdir data/yearly-avg-pkz-files")
#---| os.system("./pntcomp2/pnt-to-pkz -o data/yearly-avg-pkz-files data/yearly-avg-pnt-files")


#####
##### 2. Compute 22-year running averages in dir _data/22year-running-averages_:
#####
#---| os.system("mkdir data/22year-running-averages")
#---| files = [("data/yearly-avg-pkz-files/%s" % file) for file in sorted(os.listdir("data/yearly-avg-pkz-files")) if re.search('.pkz$', file)]
#---| os.system("./pntcomp2/pkz-avg --count=22 --outfile-pattern='%s.pkz' --outdir=data/22year-running-averages " + " ".join(files))

#####
##### 3. Compute the baseline, 1901-1960 average, saving it to file _data/baseline/tavg-1901-1960.pkz_:
#####
#---| os.system("mkdir data/baseline")
#---| files = [("data/yearly-avg-pkz-files/%04d.pkz" % y) for y in range(1901,1961)]
#---| os.system("./pntcomp2/pkz-avg --outfile=data/baseline/tavg-1901-1960.pkz " + " ".join(files))


#### 
#### 4. Compute the anomaly, relative to the above baseline, of each 22year avg, saving results
####    to files in data/22year-anomalies
#### 
#---| os.system("mkdir data/22year-anomalies")
#---| files = [file for file in os.listdir("data/22year-running-averages") if re.search('.pkz$', file)]
#---| for file in files:
#---|     os.system("./pntcomp2/pkz-subtract data/22year-anomalies/%s %s data/22year-running-averages/%s" %
#---|               (file, "data/baseline/tavg-1901-1960.pkz", file))

####
#### 5. Generate contour files for each anomaly file in data/22year-anomalies, storing the results
####    in data/22year-anomaly-contours
####
os.system("mkdir data/22year-anomaly-contours")
os.system("./pntcomp2/pkz-contour --values=-9999,-0.833,-0.556,-0.278,0.0,0.278,0.556,0.833,9999"
          + " -o data/22year-anomaly-contours data/22year-anomalies")

###   Run pkz-to-contour-json on each pkz file found in data/final/22year-anomalies, generating
###   the corresponding json file, which will also be stored in data/final/22year-anomalies.

### * pkz-to-contour-json
### 
###   Load a single pkz file and generate a json contour file from it.
### 
### * jsonify-22year-anomalies
### 
### 
### * dopages
### 
###   Use phantomjs to render an image for each contour json file in data/final/22year-anomalies;
###   store the images in data/final/22year-anomaly-images.
### 
### * generate-animated-gif
### 
###   Generate a single animated gif image from all the images found in data/final/22year-anomaly-images
